baseURL: https://floridaman7588.me/
languageCode: en-us
title: "FloridaMan's Site"
theme: profile

outputs:
  home:
    - "HTML"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 5
enableEmoji: true
enableRobotsTXT: true
disqusShortname: FloridaMan7588

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "About"
      weight: 2
      url: "/about/"
    - name: "Contact"
      weight: 3
      url: "/contact/"
    - name: "Projects"
      weight: 4
      url: "/projects/"
    - name: "Blog"
      weight: 5
      url: "/blog/"

params:
  title: "FloridaMan's Site"
  description: "FloridaMan7588's personal blog and website. Find information about projects, my personal life, or whatever I'm interested in at the moment."
  favicon: "/favicon.ico"
  useBootstrapCDN: false
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left

  navbar:
    align: ms-auto
    showBrandLogo: false
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: false
    
    hero:
      enable: true
      intro: "Hello, I'm"
      title: "Cayden"
      subtitle: "But you can call me FloridaMan"
      content: "I like to make things online, I'm not very good but I do it. I also enjoy singing, and sometimes playing video games. Sometimes I stream on YouTube, although I haven't uploaded there in a couple of years. I'll talk about my shenanigans here, and sometimes I write on Mastodon too."
      bottomImage: 
        enable: false
      roundImage: false
      button:
        enable: false
      socialLinks:
        fontAwesomeIcons:
          - icon: fab github-alt
            url: https://fm7588.me/github
          - icon: fab mastodon
            url: https://fm7588.me/mastodon
          - icon: fab link
            url: https://fm7588.me/littlelink
    
    about:
      enable: true
      title: "About Me"
      content: |-
        I'm a 15 year old high school student who likes to make things online. I'm not very good at it, but I do it. I also enjoy singing, and sometimes playing video games. Sometimes I stream on YouTube, although I haven't uploaded there in a couple of years. I'll talk about my shenanigans here, and sometimes I write on Mastodon too.
      skills:
        enable: true
        title: "Some things I can kinda do"
        items:
          - "Web Design and HTML"
          - "(Cosplaying as a )Systems Administrator"
          - ""